from package_203_project.modified_portfolio_methods import SharpeRatioMaximization, EqualWeightPortfolio
from pybacktestchain.broker import FirstTwoMoments
from package_203_project.package_203_project import configure_and_run_backtest

configure_and_run_backtest()

